# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Release

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.9.0'
  displayName: 'Install Node.js'
  
- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: $(Build.Repository.LocalPath)/Application_ts

- script: |
    tsc --build
  displayName: 'Build Typescript to JS'
  workingDirectory: $(Build.Repository.LocalPath)/Application_ts

- task: CopyFiles@2
  displayName: 'Copy Transpiled JS to $(Build.StagingDirectory)'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/Application'
    Contents: '**'
    TargetFolder: '$(Build.StagingDirectory)'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy npm dependancies to $(Build.StagingDirectory)'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/Application_ts/node_modules'
    Contents: '**'
    TargetFolder: '$(Build.StagingDirectory)/node_modules'
    CleanTargetFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.StagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.StagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish $(Build.StagingDirectory) to Azure Pipelines'
  inputs:
    PathtoPublish: '$(Build.StagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'AdminPortal-Services-TST-PROD-$(Build.BuildNumber)'
    publishLocation: 'Container'
